version: '3.8'

services:
  rec_db:
    container_name: rec_db
    image: postgres:16.0
    env_file:
     - .env
    environment:
      POSTGRES_DB : rec_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/rec_svc_postgres
    volumes:
      - rec-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  course_db:
    container_name: course_db
    image: postgres:16.0
    env_file:
     - .env
    environment:
      POSTGRES_DB : course_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/course_svc_postgres
    volumes:
      - course-db:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  rec-db:
  course-db: