kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: list-deployments-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]