# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course_svc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ourse_svc.proto\"\x16\n\x08\x43ourseId\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\tCourseIds\x12\x0b\n\x03ids\x18\x01 \x03(\t2;\n\rCourseService\x12*\n\x13GetCourseIdsForUser\x12\x07.UserId\x1a\n.CourseIdsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_svc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COURSEID']._serialized_start=20
  _globals['_COURSEID']._serialized_end=42
  _globals['_USERID']._serialized_start=44
  _globals['_USERID']._serialized_end=64
  _globals['_COURSEIDS']._serialized_start=66
  _globals['_COURSEIDS']._serialized_end=90
  _globals['_COURSESERVICE']._serialized_start=92
  _globals['_COURSESERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
